# This is the default config file for bcedd

paths:
    # erddap: path of the main ERDDAP repository [tomcat]
    erddap: '/home/jpa029/Code/apache-tomcat-8.5.57'
    # webinf: path to the 'WEB-INF' repository
    webinf: '/home/jpa029/Code/apache-tomcat-8.5.57/webapps/ROOT/WEB-INF'
    # dataset: path where store file from each dataset
    dataset:
        # path where store xml file for each remote ERDDAP server
        xml: '/home/jpa029/Data/BC-ERDDAP/dataset/xml'
    # log: path where store output log file
    log: '/home/jpa029/Data/BC-ERDDAP/log'

# log:
log:
    # filename: logger filename
    filename:
    # below, apply only on standard output log
    # TODO find a way to make it work, overwrite by argument
    # verbose: activate verbose mode [True|False]
    verbose: False
    # level: log level [DEBUG, INFO, WARN, ERROR, CRITICAL]
    level: 'INFO'

authorised:
    # eddtype: list of authorised eddtype
    eddtype: ['table', 'grid']
    # frequency: list of authorised frequency
    frequency: ['weekly', 'monthly']

# update:
update:
    # freq: update frequency to be applied ['weekly', 'monthly']
    freq: 'monthly'

extra:
    # parameters: extra parameters configuration file for bcedd
    parameters: 'parameters.yaml'
